### PR TITLE
improve npm package manifest

### PR DESCRIPTION
**Pull request by atwright147**
Improvements include:

* align name with bower.json
* align description with bower.json
* add homepage (aligned with bower.son content)
* align main with bower.json
* add same keywords as bower.json
* add MIT license (same as bower.json)

### CODE REVIEW

**Comment by atwright147** [comment]
Would you mind adding this to the NPM Registry ASAP please? :)

**Comment by rsboarder** [comment]
+1

**Comment by JobaDiniz** [comment]
+1

**Comment by aaronroberson** [comment]
@atwright147 Due to merge conflicts I had to make these updates myself. Thank you for pointing them out. I've also reached out to @enriquecastl for permissions to publish to npm with the package name `ng-mask` (npm doesn't allow camelCase).

**Pull request closed without merging**
