### PR TITLE
Reload mask when change mask done and validation fixed

### PR DESCRIPTION
**Pull request by guilhermegm**
I made a lot of chances sinse my last commit about mask change. I hope at least to help you in some way.

Thank you

### CODE REVIEW

**Comment by MarcMeszaros** [comment]
This would be useful and exactly solve what I need. Hope this get's merged soon!

**Comment by noblezilla** [comment]
+1

**Comment by adrienemery** [comment]
+1

**Comment by nessauepa** [comment]
+1

**Comment by JobaDiniz** [comment]
+1

**Comment by JobaDiniz** [comment]
+1

I think you should also add an example in the sample pages as part of this change: https://github.com/candreoliveira/ngMask/tree/master/examples

**Comment by fabiowitt** [comment]
Please, this.

**Comment by joeylgutierrez** [comment]
please merge this!!

**Pull request merged**
